# Generated by Django 4.0 on 2022-01-04 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hsUser',
        ),
    ]
