# Generated by Django 4.0 on 2022-01-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projeto', '0002_delete_hsuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='hsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsUserID', models.CharField(max_length=100, unique=True)),
                ('hsUserName', models.CharField(max_length=100)),
            ],
        ),
    ]
